baseURL = "https://VigneshJM99.github.io/mlnotes/"
languageCode = "en-us"
title = "Vignesh"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
